[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000 ; includeSubDomains"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; img-src *; media-src *; script-src benfrancom.com https://www.benfrancom.com https://*.googleapis.com https://fonts.gstatic.comi; style-src 'self' https://*.googleapis.com; frame-src 'self' https://archive.org https://*.youtube.com"


[[redirects]]
  from = "/2014/11/24/mutt-offline-with-mbsync/"
  to = "https://www.benfrancom.com/2014/mutt-offline-with-mbsync/"
  status = 200
  force = true
